### ISSUE TITLE
Tab on last cell to go to next row

### ISSUE THREAD

**Issue by kdabir** [renanlecaro/importabular#1]
When editing thru a row, key-pressing `tab` on the last cell should take the focus to next row's first cell.

![tabs](https://user-images.githubusercontent.com/735240/94340387-e5d6a380-001e-11eb-8d1b-af79930d0355.gif)

PS: And it's understandable you may not want to include this in the core library. In that case, any pointers in documentation to achieve such behavior would be a great help.

**Comment by renanlecaro** [comment]
Yeah, this part needs rework, i think it's in scope as it's a basic excel feature that's poorly replicated.

**Comment by renanlecaro** [comment]
I've implemented this for the case where a user has a selection (also, support for enter cycling though the selection). 

When the user doesn't have a selection to tab into it's a bit more complicated so i've left it out for now.

**Comment by renanlecaro** [comment]
Feature is now implemented, event without a selection, closing :)
