### ISSUE TITLE
class-properties, vuejs, and babel

### ISSUE THREAD

**Issue by DocBouCou** [renanlecaro/importabular#2]
Hi,

Just to let you know that, as importabular is using class properties, it may not work with vuejs (in my case: vue 2, using vue-cli 3 and babel). I had to add a babel-plugin `plugin-proposal-class-properties` to make it work. You can read at the answer I just made on stackoverflow ([here](https://stackoverflow.com/questions/59834578/vuejs-use-babel-plugin-proposal-class-properties/64241331#64241331)).
This is not really an issue concerning your code. But, as it never happened to me before and I spent/lost a few hours on it, I thought you might write something about it in the docs.
Anyway, thanks for your lib. I also need a simple minimalist spreadsheet, and, now that I made it work with vue it really helps me :) .

**Comment by renanlecaro** [comment]
Oh yeah i guess I could at least apply the transform to the build version, so that the default import works without Babel plugins

**Comment by renanlecaro** [comment]
@DocBouCou is the problem still there with version 0.1.2 ?
