### ISSUE TITLE
Input too wide when editing

### ISSUE THREAD

**Issue by DocBouCou** [renanlecaro/importabular#3]
When editing a cell, I got a much wider input. For instance, the `td` was 100px wide, while the `input` was "browser-default-wide". At least in Firefox, the input was about 238px. So, it got ugly. 

Looking at the code, it seems that the `style` of the input was not actually modified. So, I made some change in `_startEditing` :

```javascript
_startEditing({ x, y }) {
    this._editing = { x, y };
    const td = this._getCell(x, y);
    const tdSize = td.getBoundingClientRect();
    const cellSize = td.firstChild.getBoundingClientRect();

    Object.assign(td.style, {
      width: tdSize.width-2,
      height: tdSize.height,
    });

    const input = document.createElement("input");
    input.type = "text";
    input.value = this._getVal(x, y);

    Object.assign(input.style, {
      width: `${cellSize.width}px`, 
      height: `${cellSize.height}px`,
    });
    td.removeChild(td.firstChild); //it was before assignment of style, maybe causing the issue
    td.appendChild(input);
    input.focus();
    input.addEventListener("blur", this._stopEditing);
    input.addEventListener("keydown", this._blurIfEnter);
  }
```

Well, I do not know how to make a pull request etc., but you can probably just copy-paste these few lines.

Regards,

**Comment by renanlecaro** [comment]
I'll have a look once I'm on my computer, thanks

**Comment by renanlecaro** [comment]
I couldn't reproduce, but adding the px unit to the style seemed like a good idea so i added that. I don't think the deletion of the div node should have any impact, as the measurement have already been done anyway.

**Comment by renanlecaro** [comment]
The latest version should include those changes
