### ISSUE TITLE
Adding new fields after the table is rendered

### ISSUE THREAD

**Issue by badrihippo** [renanlecaro/importabular#6]
Hi! I've just started a project that uses importabular, and it's pretty neat!

One thing I would find very useful, though, is the ability to control the rows and columns a bit more, or at least add new columns once the table is rendered. Do you think this is something that would fit with the minimalist mode you're going for? (I know you'd want to avoid feature creep, so it's fine if you don't want it; just wanted to check and make sure :slightly_smiling_face:)

**Comment by renanlecaro** [comment]
Hi

I'm not sure what your use case looks like, but I think it would be easy for you to 

- copy the data of the instance `const oldData=sheet.getData();`
- destroy the instance `sheet.destroy()`
- rebuild it with the new columns
-  set the data back `newSheet.setData(oldData);`. 

This way you can control how the existing data moves from one column to another.

**Comment by badrihippo** [comment]
Oh yes, I was thinking of doing something along these lines too. Thanks for putting it down systematically though!

What I originally had in mind on creating this issue was a "delete the *n*th column" API, but maybe that was just me being lazy. Manual rebuilding will do for now :slightly_smiling_face:

**Comment by renanlecaro** [comment]
To be fair, the lib could be a bit better for this (with getter and setters for the selection / focused cell / edited cell. 
The UX of having the table flash is not optimal.

**Comment by badrihippo** [comment]
In case someone else stumbles upon this, here's my implementation (used in [this project](https://gitlab.com/snipettemag/chipchoc)). It's been lightly edited to be more generically useful:

```js
function refreshSheet(sheet, editor, newColList) {
	let oldData = sheet.getData()
	let oldColumns = sheet.columns.map(c => c.label)

	// get rid of the old sheet
	sheet.destroy()

	// now, make it up again with the new columns
	let columns = []

	for (let col of colList) {
		columns.push({
			label: col,
		})
	}

	sheet = new Importabular({
		node: editor,
		columns: columns,
	})

	// figure out the new data
	let newData = []
	let colOrder = []

	// first, we figure out how the old column order corresponds to
	// the new one

	for (let col of sheet.columns.map(c => c.label)) {
		colOrder.push(oldColumns.indexOf(col))
	}

	// now we fill this, row by row
	for (let oldRow of oldData) {

		// skip empty rows
		if (oldRow.every(v => !v)) continue

		// now, we figure out what to put for the new row
		let newRow = []
		for (let colIndex of colOrder) {
			if (colIndex <= -1) {
				// new column; leave it blank
				newRow.push('')
			} else {
				// old column; keep it filled!
				newRow.push(oldRow[tkIndex])
			}
		}

		// and finally, when all is done, we save it.
		newData.push(newRow)
	}

	// fill it with the new data
	sheet.setData(newData)
	return sheet
}
```
Disclaimer: this code hasn't been tested, but it *should* work. You can see the original running version [https://gitlab.com/snipettemag/chipchoc/-/blob/master/src/App.svelte](here). Note that in the original, columns are referred to as "TKs" or `tkList`, since it's a table of "TKs", which is publisher's jargon for "things to be filled".
