### ISSUE TITLE
Copy paste from O365 Excel and Excel for Mac does not work

### ISSUE THREAD

**Issue by LukasGutwinski** [renanlecaro/importabular#9]
Hello Renan,

First of all thank you for creating importabular. It seems to be the perfect solution for my usecase and I very much like that it's lightweight and also looks nice.

When testing importabular I noticed that copy pasting data from O365 Excel and Excel for Mac does not work for me. All data gets pasted into a single field also if multiple rows and columns were selected:
![CleanShot 2022-09-09 at 21 38 36](https://user-images.githubusercontent.com/20278944/189430539-01b83efb-1e70-49b2-9927-1402eae93bb7.gif)

I tried to dig a bit deeper into the code of importabular but was not able to fix it yet. I will have a closer look next week.

Do you know what could be the reason for this behaviour?

Regards from Vienna,
Lukas

**Comment by renanlecaro** [comment]
@LukasGutwinski i finally found the time to look at this. I had a check to ignore keyboard events with "ctrlKey" set but not one for "metaKey". After testing on a mac i could copy/paste correctly on 0.2.11
